server:
  port: 8888

spring:
  application:
    name: commerce-platform-config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/mohammed-addoumi/commerce-platform-config.git
          clone-on-start: true
          default-label: main